language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - functions/node_modules
script:
 - npm run build
install:
  - npm install
  - cd functions && npm install && cd -
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
