language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
 - npm run build
install:
  - npm install
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
