language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - functions/node_modules
install:
  - npm install -g
script:
 - npm run build
before_deploy: cd functions && npm install
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
