language: node_js
node_js:
  - "7"
script:
 - npm run build
install:
  - npm install -g firebase-tools
  - npm install -g react-scripts
after_success:
  - firebase deploy --project crapper-keeper --token $FIREBASE_TOKEN